font:
  size:
    heading_huge: 18pt
    heading_large: 13pt
    heading: 11pt
    description: 8pt
    tags: 8pt
    education_description: 8pt
    contacts: 8pt
  display: "HK Grotesk"
  basic: "Inter"

paragraph:
  # Distance between lines
  leading: 5pt
